In [20]:
import pandas as pd
import numpy as np

data = pd.read_csv('train.csv')
print(data)
data = np.array(data)
m ,n = data.shape
np.random.shuffle(data)

# data = data.T
# display(data)


print(data)
data_train = data[0:2000].T
labels_train = data_train[0]
x_train = data_train[1:n]

x_train = (x_train - np.min(x_train))/(np.max(x_train) - np.min(x_train))

data_test = data[2000:m].T
labels_test = data_test[0]
x_test = data_test[1:n]/255.0
x_test = (x_test - np.min(x_test))/(np.max(x_test) - np.min(x_test))

# x_train = x_train / 255.0
# np.random.shuffle(x_train)
print(f'labels {labels_train}')
print(x_train)

x_train.shape

def init_params():
    w1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    w2 = np.random.rand(10,10)- 0.5
#     print(w2.shape)
    b2 = np.random.rand(10,1)- 0.5
    return w1, b1, w2, b2

w1, b1, w2, b2 = init_params()

def RelU(z):
    relU = np.maximum(z, 0)
#     print(f'relu : {relU}')
    return relU

def softmax(z):
    # z = z - np.max(z)
    e_z = np.exp(z)
    softmax = e_z/sum(e_z)

    return softmax

def forward_prop(x,w1,b1,w2,b2):
    # print(b1.shape)
    z1 = w1.dot(x) + b1
    a1 = RelU(z1)
    z2 = w2.dot(a1) + b2
    a2 = softmax(z2)
    
    return z1, a1, z2, a2


def one_hot(y):
    one_hot = np.zeros((y.size, y.max() + 1))
    one_hot[np.arange(y.size), y] = 1
    one_hot = one_hot.T
    return one_hot

def deriv_RelU(z):
    return z > 0
    # return np.where(z > 0, 1, 0)



def back_prop(z1,a1,w2,a2, x, y):
    one_hot_y = one_hot(y)
    
    m = y.size
#     C0 = np.zeroes(10,1)
    error2 = a2 - one_hot_y
    # print(error2[0])
    dw2 = error2.dot(a1.T)/m
    db2 = np.sum(error2)/m

    error1 = w2.T.dot(error2) * deriv_RelU(z1)
    dw1 = error1.dot(x.T)/m
    db1 = np.sum(error1)/m
    
    return dw1, db1, dw2, db2


def update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, rate):
#     print(f'first : w1, b1, w2, b2 : {w1} {b1} {w2} {b2}')
    w1 = w1 - rate * dw1
    b1 = b1 - rate * db1
    w2 = w2 - rate * dw2
    b2 = b2 - rate * db2
    
#     print(f'changed: w1, b1, w2, b2 : {w1} {b1} {w2} {b2}')

    return w1, b1, w2, b2

       label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775 

In [21]:
def get_predictions(a):
#     display(a[:,0] == a[:,1])
    # print('activation layer')
    # display(a)
    # print(a.shape)
#     print(np.argmax(a,1))
    return np.argmax(a, 0)

def get_accuracy(predictions, y):
    # print(predictions, y)
    return np.sum(predictions == y) / y.size

def run(x, y, iterations, rate):
    w1, b1, w2, b2 = init_params()
    last_accuracy = 0
    first = 0
#     print(w2.shape)
    for iteration in range(iterations):
        z1, a1, z2, a2 = forward_prop(x, w1, b1, w2, b2)
        dw1, db1, dw2, db2 = back_prop(z1, a1, w2, a2, x, y)
        w1, b1, w2, b2 = update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, rate)

        if iteration == 1:
                first = p
                
        if iteration % 10 == 0:
            print(f'iteration : {iteration}')
            p = get_accuracy(get_predictions(a2), y)
            print(f'accuracy : {p}, {p > last_accuracy}')
            
            last_accuracy = p
    print(f'improvement : {last_accuracy - first}')
    return w1, b1, w2, b2

In [22]:
w1, b1, w2, b2 = run(x_train, labels_train, 1500, .12)

iteration : 0
accuracy : 0.138, True
iteration : 10
accuracy : 0.1835, True
iteration : 20
accuracy : 0.217, True
iteration : 30
accuracy : 0.252, True
iteration : 40
accuracy : 0.285, True
iteration : 50
accuracy : 0.338, True
iteration : 60
accuracy : 0.3995, True
iteration : 70
accuracy : 0.4475, True
iteration : 80
accuracy : 0.4965, True
iteration : 90
accuracy : 0.5485, True
iteration : 100
accuracy : 0.5875, True
iteration : 110
accuracy : 0.614, True
iteration : 120
accuracy : 0.6385, True
iteration : 130
accuracy : 0.662, True
iteration : 140
accuracy : 0.679, True
iteration : 150
accuracy : 0.6975, True
iteration : 160
accuracy : 0.7155, True
iteration : 170
accuracy : 0.728, True
iteration : 180
accuracy : 0.7395, True
iteration : 190
accuracy : 0.748, True
iteration : 200
accuracy : 0.7565, True
iteration : 210
accuracy : 0.768, True
iteration : 220
accuracy : 0.776, True
iteration : 230
accuracy : 0.7835, True
iteration : 240
accuracy : 0.792, True
iteration : 250
accuracy

In [23]:
def continue_learning(w1, b1, w2,b2, iterations, rate, x, y):
    for iteration in range(iterations):
        z1, a1, z2, a2 = forward_prop(x, w1, b1, w2, b2)
        dw1, db1, dw2, db2 = back_prop(z1, a1, w2, a2, x, y)
        w1, b1, w2, b2 = update_params(w1, b1, w2, b2, dw1, db1, dw2, db2, rate)

        if iteration % 10 == 0:
            print(f'iteration : {iteration}')
            p = get_accuracy(get_predictions(a2), y)
            print(f'accuracy : {p}')
            

def make_predictions(x, w1, b1, w2, b2):
    _, _, _, a2 = forward_prop(x, w1, b1, w2, b2)
    predictions = get_predictions(a2)
    return predictions


# test_data = pd.read_csv('test.csv')
# test_data = np.array(test_data)
# m, n = test_data.shape
# test_data = test_data.T
# test_labels = test_data[0]
# test_x = test_data[0:n]/255.0

preds = make_predictions(x_test, w1, b1, w2, b2)

print(get_accuracy(preds, labels_test))


            # last_accuracy = p
    # print(f'improvement : {last_accuracy - first}')

# continue_learning(w1, b1, w2, b2, 2000, .0006, x_train, labels_train)


0.8575


In [25]:
def init_params():
    w1 = np.random.rand(12,784) - 0.5
    b1 = np.random.rand(12,1) - 0.5
    w2 = np.random.rand(12,12) - 0.5
    b2 = np.random.rand(12,1) - 0.5
    w3 = np.random.rand(10,12)- 0.5
    b3 = np.random.rand(10,1)- 0.5
    return w1, b1, w2, b2, w3, b3

def RelU(z):
    relU = np.maximum(z, 0)
    return relU

def softmax(z):
    e_z = np.exp(z)
    softmax = e_z/sum(e_z)
    return softmax

def forward_prop(x,w1,b1,w2,b2,w3,b3):
    z1 = w1.dot(x) + b1
    a1 = RelU(z1)
    z2 = w2.dot(a1) + b2
    a2 = RelU(z2)
    z3 = w3.dot(a2) + b3
    a3 = softmax(z3)
    # print(a2.shape)
    
    return z1, a1, z2, a2, z3, a3


def one_hot(y):
    one_hot = np.zeros((y.size, y.max() + 1))
    one_hot[np.arange(y.size), y] = 1
    one_hot = one_hot.T
    return one_hot

def deriv_RelU(z):
    return z > 0
    # return np.where(z > 0, 1, 0)



def back_prop(a1, w1, z1, a2, w2, z2, a3, w3, z3, x, y):
    one_hot_y = one_hot(y)
    
    m = y.size
#     C0 = np.zeroes(10,1)
    dz3 = a3 - one_hot_y
    # print(error2[0])
    dw3 = dz3.dot(a2.T)/m
    db3 = np.sum(dz3)/m

    error2 = w3.T.dot(dz3) * deriv_RelU(z2)
    dw2 = error2.dot(a1.T)/m
    db2 = np.sum(error2)/m

    error1 = w2.T.dot(error2) * deriv_RelU(z1)
    dw1 = error1.dot(x.T)/m
    db1 = np.sum(error1)/m
    
    return dw1, db1, dw2, db2, dw3, db3


def update_params(w1, b1, w2, b2, w3, b3, dw1, db1, dw2, db2, dw3, db3, rate):
#     print(f'first : w1, b1, w2, b2 : {w1} {b1} {w2} {b2}')
    w1 = w1 - rate * dw1
    b1 = b1 - rate * db1
    w2 = w2 - rate * dw2
    b2 = b2 - rate * db2
    w3 = w3 - rate * dw3
    b3 = b3 - rate * db3
    
#     print(f'changed: w1, b1, w2, b2 : {w1} {b1} {w2} {b2}')

    return w1, b1, w2, b2, w3, b3

def get_predictions(a):
    return np.argmax(a, 0)

def get_accuracy(predictions, y):
    print(predictions, y)
    return np.sum(predictions == y) / y.size

def gradient_descent(x, y, iterations, rate):
    w1, b1, w2, b2, w3, b3 = init_params()
    # last_accuracy = 0
    # first = 0
    load = '----------------------------------------------------------|'
    # bar = ''

    # dist = ''
    for _ in range(iterations):
        z1, a1, z2, a2, z3, a3 = forward_prop(x, w1, b1, w2, b2, w3, b3)
        dw1, db1, dw2, db2, dw3, db3 = back_prop(a1, w1, z1, a2, w2, z2, a3, w3, z3, x, y)
        w1, b1, w2, b2, w3, b3 = update_params(w1, b1, w2, b2, w3, b3, dw1, db1, dw2, db2, dw3, db3, rate)
        # dist = int((len(load)*iteration)/iterations)
        # bar = ['*']*dist
        # loader = [*load]
        # # print(loader)
        # loader[0:dist] = bar
        # # loader.append()
        # load = ''.join(loader)
        # if iteration == 1:
                # first = p
                
        # if iteration % 50 == 0:
        #     print(f'iteration : {iteration}')
      
        p = get_accuracy(get_predictions(a3), y)
        # print(load)
        print(f'{p}')
        

        
        
            # last_accuracy = p
    # print(f'improvement : {last_accuracy - first}')
    return w1, b1, w2, b2, w3, b3


w1, b1, w2, b2, w3, b3 = gradient_descent(x_train, labels_train, 2000, .08)

[8 1 8 ... 8 8 8] [4 3 0 ... 4 5 9]
0.097
[8 1 8 ... 8 8 8] [4 3 0 ... 4 5 9]
0.0975
[0 1 8 ... 8 8 8] [4 3 0 ... 4 5 9]
0.1015
[0 1 8 ... 8 8 8] [4 3 0 ... 4 5 9]
0.1055
[0 1 8 ... 8 3 8] [4 3 0 ... 4 5 9]
0.107
[0 1 8 ... 8 3 8] [4 3 0 ... 4 5 9]
0.1085
[0 1 8 ... 8 3 8] [4 3 0 ... 4 5 9]
0.104
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.107
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.109
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.112
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.1165
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.1225
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.1305
[0 1 0 ... 3 3 8] [4 3 0 ... 4 5 9]
0.136
[0 1 0 ... 3 3 8] [4 3 0 ... 4 5 9]
0.139
[0 1 0 ... 3 3 8] [4 3 0 ... 4 5 9]
0.142
[0 1 0 ... 3 3 8] [4 3 0 ... 4 5 9]
0.143
[0 1 0 ... 3 3 8] [4 3 0 ... 4 5 9]
0.146
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.149
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.15
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.152
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.1535
[0 1 0 ... 1 3 8] [4 3 0 ... 4 5 9]
0.154
[0 1 0 ... 1 3 8] [4 3 0 ..